---
title: "Clases"
description: |
  En esta pestaña se irán subiendo las presentaciones de las clases a medida que se vayan ejecutando. 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introducción al curso y a R

[Clase 1. Bloque 1 y 2](clases/clase1/clase1.html)

# La metodología cuantitativa y R base

[Clase 2. Bloque 1 teórico](clases/clase2/clase2a.html)

[Clase 2. Bloque 2 práctico](clases/clase2/clase2b.html)

# Tipos de datos cuantitativos, proceso estadístico e introducción a dplyr

[Clase 3. Bloque 1 teórico](clases/clase3/clase3a_tipos.html)

[Clase 3. Bloque 2 práctico](clases/clase3/clase3b_dplyr.html)

# Diseños de investigación: entre la observación y la experimentación; y la descripción y la causalidad

[Clase 4. Bloque 1 teórico](clases/clase4/clase4a_diseno.html)

[Clase 4. Bloque 2 práctico](clases/clase4/clase4b_rproj.html)

# Investigación por encuestas; principales encuestas en Chile y como importarlas en R

[Clase 5. Bloque 1 teórico](https://opso791ucsh2021.netlify.app/clases/clase5/clase5a_cuestionarios.html#1)

[Clase 5. Bloque 2 práctico](https://opso791ucsh2021.netlify.app/clases/clase5/clase5b_help_import.html#1)

# Prueba 1 (24 de septiembre)

[Descargar pauta](pruebas/prueba1.pdf)

# Clase de consolidación aprendizajes en R (01 de octubre)

[Clase 6. Revisión prueba 1](https://opso791ucsh2021.netlify.app/clases/clase6/clase6a_correccion_prueba#1)

[Clase 6. Pipe, profundización dplyr y buen código](https://opso791ucsh2021.netlify.app/clases/clase6/clase6b_pipe_dplyr_codigo#1)

# Pendientes clase 6, revisión tarea 3 y estadística descriptiva (08 de octubre)

[Clase 7. Revisión tarea 3 y recuperación sesión 6](https://opso791ucsh2021.netlify.app/clases/clase7/clase7a_pendiente_dplyr_codigo#1)

[Clase 7. Estadística descriptiva I](https://opso791ucsh2021.netlify.app/clases/clase7/clase7b_estadistica_descriptiva#1)

# No hubo clases el 15 de octubre

# Prueba 2 (22 de octubre)

[Descargar pauta](pruebas/prueba2.pdf)

# Estadística descriptiva II (29 de octubre)

[Clase 8. Revisión prueba 2](https://opso791ucsh2021.netlify.app/clases/clase8/clase8a_correccion_prueba2#1)

[Clase 8. Estadística descriptiva II](https://opso791ucsh2021.netlify.app/clases/clase8/clase8b_estadistica_descriptiva2#1)

[Clase 8. Continuar agrupación y pivotaer data frames](https://opso791ucsh2021.netlify.app/clases/clase8/clase8c_agrupar_trasponer#1)

# Visualización de datos (y continuar trasponer y combinar data) (05 de noviembre)

[Clase 9. Continuación pivotear y combinación de data frames](https://opso791ucsh2021.netlify.app/clases/clase9/clase9a_trasponer_combinar#1)

[Clase 9. Visualización de datos con ggplot2](https://opso791ucsh2021.netlify.app/clases/clase9/clase9b_visualizacion#1)

# Ciencia abierta y reproducibilidad (12 de noviembre)

[Clase 10. Ciencia abierta, reproducibilidad y profundización RMarkdown](https://opso791ucsh2021.netlify.app/clases/clase10/clase10a_csabierta#1)

# Continuación taller Zotero, espacio de trabajo en tarea N°5, resolución de dudas y preparación prueba 3 (19 de noviembre)

[Clase 11. Gestión de bibliografías](https://opso791ucsh2021.netlify.app/clases/clase10/clase10c_zotero_bibtex#1)

# Prueba 3 (26 de noviembre)

# Muestras complejas e inferencia (26 noviembre o 03 de diciembre)

[Clase 12. La lógica del muestreo y la inferencia](https://opso791ucsh2021.netlify.app/clases/clase11/clase10a_muestreo#1)

[Clase 12. Hacer inferencias en R desde muestras complejas](https://opso791ucsh2021.netlify.app/clases/clase11/clase10b_survey#1)

# Prueba integrativa final (10 y 17 de diciembre)
