---
title: "Programa curso Diseño y Análisis de Datos Cuantiativos (en R)"
description: |
  Sociología, Universidad Católica Silva Henríquez
author:
  - name: Nicolás Ratto
    url: https://www.researchgate.net/profile/Nicolas-Ratto 
date: "`r Sys.Date()`"
journal: "Borrador"
output: 
 distill::distill_article:
   toc: true
   toc_depth: 2
   toc_float: TRUE
# rmarkdown::render(input = "programa.Rmd", output_format = "pdf_document")
bibliography: [bibliografia/bib.bib]
link-citations: true
nocite: |
 @Asun2006, @Burawoy1990, @Agresti2018, @Schmitter2013, @Corbetta2007, @Breznau2021, @Healy2018, @Vivanco2006
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Pre-requisitos (*)

Teoría sociológica

Metodología de la Investigación Cuantitativa

# Descriptor

El curso busca entregar una comprensión general del proceso de investigación social cuantitativa y herramientas que permitan elaborar y ejecutar diseños de investigación utilizando el lenguaje R y otras herramientas de la ciencia abierta.

# Condiciones de entrada

-	Sabe problematizar fenómenos de investigación desde la perspectiva cuantitativa.
-	Reconoce el contenido de un diseño de investigación cuantitativa.
-	Sabe identificar y/o construir variables cuantitativas de investigación. 
- Manejo básico de teoría sociológica (al menos los clásicos Weber, Marx y Durkheim)

# Aprendizajes esperados

+ Comprender el contexto epistemológico en que se desarrolla la investigación social

+ Conocer el panorama de instrumentos de medición y tipos de estudios cuantitativos

+ Interpretar y analizar los elementos centrales de una base de datos con información social

+ Aplicar las técnicas más pertinentes de estadística descriptiva según las distintas características de los datos (en lenguaje R).

+ Presentar de manera visual y efectiva los datos cuantitativos (en lenguaje R).

+ Comprender la lógica de construcción de índices, escalas y tipologías

+ Conocer y ejecutar junto a R otras herramientas y lenguajes de la ciencia abierta (Markdown, Zotero, Github, entre otras)


# Contenidos de la actividad curricular

## I. Epistemología y consideraciones generales sobre la ciencia

a. Fundamentos epistemológicos de la investigación social cuantitativa.
b. Traducción empírica de la teoría: hipótesis, conceptos, dimensiones, indicadores, variables, unidades de análisis y unidades de observación.
c. Programas de investigación en ciencias sociales
d. Apertura y reproducibilidad de la investigación social.

## II. Diseños de investigación social

a. Diseños de Investigación cuantitativos: descriptivo, correlacional, causal; observacional, experimental. 
b. Instrumentos de producción y ordenamiento de la información: encuestas, bases de datos agregadas, registros administrativos, análisis de contenido cuantitativo, codificación de prensa.
c. Estructura de las bases de datos: Datos de corte transversal; Datos de series de tiempo; Combinación de cortes transversales; y Datos de panel o longitudinales.

## III. Tipos de datos cuantitativos, estructura de los datos, muestras, inferencia y análisis pertinentes (estadísticas)

a. Tipos de datos cuantitativos (nominales, ordinales, numéricos)
b. Estructura de los datos (estructurados y des estructurados; transversales y longitudinales)
c. La lógica del muestreo. Como conocer lo totalidad a partir de una parte (inferencia). Tipos de muestreo: muestreo aleatorio simple, muestreo estratificado, muestreo por conglomerados.
d. Estimadores y parámetros.
e. Pesos, factores de expansión y medidas de precisión de las inferencias (intervalos de confianza principalmente)
f. Variables latentes. Construcción de indicadores, índices y tipologías.

## IV. Lenguajes y herramientas para el análisis de datos y reporte (R)

a. Introducción a R y R-Studio.
b. Introducción a RMarkdown
b. Manipulación de bases de datos con funciones de R base y paquete dplyr: ﬁltrar, agregar, ranquear, combinar, recodificar y crear nuevas variables a partir de otras.
c. Construcción de tablas univariadas y de contingencia.
d. Elaboración de gráﬁcos de cajas, gráficos de barras, gráﬁcos de dispersión, histogramas y gráﬁcos de densidad con funciones de ggplot2.
e. Elaborar reportes descriptivos y reproducibles con RMarkdown. 


# Criterios metodológicos de la actividad curricular

El curso se realizará por medio de la plataforma *zoom* al menos durante agosto y septiembre, donde la metodología será una combinación de clases expositivas y de ejercicios prácticos. En la exposición se presentarán los contenidos de la sesión, usando distintos ejemplos a partir de datos reales y de preguntas concretas que surgen a partir de materias de interés sociológico. En este espacio se responderán dudas y discutirá la materia, por lo que se espera una participación de los estudiantes. Luego, se realizarán ejercicios prácticos para aplicar lo aprendido en clases en modalidad de taller virtual. En este espacio, los y las estudiantes podrán ir avanzando en la realización de una aplicación práctica de la materia en su computadora personal con ayuda constante del profesor. Se trabajará con variadas bases de datos disponibles de uso público, cuyas direcciones web o archivos serán facilitadas el docente -al igual que el material de las presentaciones-. Todo el material bibliográfico estará disponible en la [plataforma](https://mc1ush2021.netlify.app/) del curso.

# Recursos didácticos de la actividad curricular. 



# Criterios evaluativos de la actividad curricular. 

La nota final del estudiante consistirá en la realización de un mini proyecto de investigación cuantitativo (30%) y la presentación de tareas prácticas (70%). Ambas serán de carácter individual.

1. **Realización de mini proyecto investigación cuantitativo:** El proyecto de investigación tendrá entregas parciales a lo largo del semestre que consistirán en 1) la pregunta de investigación, selección de base de datos a utilizar, una breve revisión bibliográfica, marco teórico e hipótesis de investigación (10%); 2) la entrega de la metodología y los resultados del análisis (10%); 3) la presentación oral del proyecto a fin de semestre y la entrega final (10%). Cada una de las etapas tendrá retroalimentación por parte del equipo docente, las que se deben ir incorporando en las siguiente entregas. 

2. **Tareas prácticas:** en la segunda sección de cada clase se dejará a disposición una guía para ser trabajada por los y las estudiantes. Dicha tarea debe ser entregada máximo tres días después de la clase.

Todas las entregas del proyecto de investigación y de las tareas deben ser enviadas al correo de Nicolás Ratto (<nicolasrattor@gmail.com>)


# Normas éticas

+ **Relación de confianza e igualdad de trato con las y los estudiantes**

Con trabajo y motivación se pueden llegar a elaborar productos de alta calidad. Se evitan controles de lectura, confiando en que la literatura será revisada clase a clase. 

La opinión de las y los estudiantes en clase es siempre válida y provechosa. 

+ **Apoyo constante en el aprendizaje y compañerismo**

R puede ser muy difícil en sus primeras aproximaciones, por lo que se requiere paciencia y apoyo de parte de las y los compañeros que les resulte más sencillo. 

+ **Reconocimiento y respeto por el trabajo e ideas de otros/as**

Se tendrá tolerancia cero ante el plagio. 

*“Plagio es el acto de presentar las ideas de otras personas como si fueran propias sin indicar la fuente de donde se obtuvo”* (Real Academia Española). 

Se considera plagio, aún sin intención de hacerlo, el hecho de copiar, adaptar, parafrasear o usar la idea, opinión o teoría de otra persona como si fuera propia sin mencionar al autor. De esta manera, instancias de plagios incluyen, entre otras, las siguientes prácticas:

+ Hacer pasar el trabajo de otra persona como propio.

+ Copiar fragmentos de la obra de otra persona palabra por palabra sin citar la fuente.

+ Parafrasear sin citar la fuente.

Cualquier instancia de plagio detectada será elevada sumariamente a las autoridades del departamento. El manejo de citas es fundamental en cualquier disciplina de investigación, de estimarlo necesario podemos dedicar parte de una de las reuniones a hacer un breve repaso de las formas de citar más comunes en ciencias sociales. 


# Recursos bibliográficos y de Información de la actividad curricular. 

## Material de apoyo

El curso cuenta con una [página web](https://dadc1ucsh2021.netlify.app/), en la cuál se irá subiendo material de apoyo para los talleres prácticos (tutoriales y manuales de R principalmente).

La bibliografía será facilitada a los/as estudiante por el profesor. En clases se señalará que capítulos o secciones de los textos son obligatorias (en el sentido de que se evaluarán sus contenidos). Al final de la página la bibliografía se encuentra listada. 

## Bibliografía





